name: Build DLL
on: [push, workflow_dispatch]
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'
      - name: Add BepInEx NuGet feed
        run: dotnet nuget add source https://nuget.bepinex.dev/v3/index.json --name bepinex
      - name: Restore
        run: dotnet restore VIMBodyTracking/VIMBodyTracking.csproj
      - name: Build
        run: dotnet build VIMBodyTracking/VIMBodyTracking.csproj -c Release --nologo --no-restore
      - uses: actions/upload-artifact@v4
        with:
          name: VIMBodyTracking-DLL
          path: "**/*.dll"
